module.exports = [
  { nombre: 'Kaguya',   kkg: 'Shikotsumyaku',       doujutsu: null                  },
  { nombre: 'Chinoike', kkg: 'Ketsuryugan',          doujutsu: 'Ketsuryugan'         },
  { nombre: 'Sabaku',   kkg: null,                   doujutsu: null                  },
  { nombre: 'Hozuki',   kkg: 'Hydrification',        doujutsu: null                  },
  { nombre: 'Yuki',     kkg: 'Hyoton',               doujutsu: null                  },
  { nombre: 'Jugo',     kkg: 'Sage Transformation',  doujutsu: null                  },
  { nombre: 'Hatake',   kkg: null,                   doujutsu: null                  },
  { nombre: 'Lee',      kkg: null,                   doujutsu: null                  },
  { nombre: 'Namikaze', kkg: null,                   doujutsu: null                  },
  { nombre: 'Mitsumi',  kkg: null,                   doujutsu: null                  },
  { nombre: 'Sarutobi', kkg: null,                   doujutsu: null                  },
  { nombre: 'Uzumaki',  kkg: null,                   doujutsu: null                  },
  { nombre: 'Nara',     kkg: null,                   doujutsu: null                  },
  { nombre: 'Senju',    kkg: 'Mokuton',              doujutsu: null                  },
  { nombre: 'Uchiha',   kkg: null,                   doujutsu: 'Sharingan (Dormido)' },
  { nombre: 'Hakari',   kkg: null,                   doujutsu: null                  },
  { nombre: 'Hyuga',    kkg: null,                   doujutsu: 'Byakugan'            },
  { nombre: 'Terumi',   kkg: 'Futton',               doujutsu: null                  },
];
